### ISSUE TITLE
Time Hover

### ISSUE THREAD

**Issue by Maximilian1021** [yanniz0r/social-network#9]
Wenn man über die Zeit hovert (also über "vor 4 Min" dann soll die genaue Zeit mit Sekunden oder so angezeigt werden...

Bspw. So :)

![grafik](https://user-images.githubusercontent.com/13157092/147879237-53a1a87f-b69e-4281-bc3b-d01f1abb912b.png)

**Comment by yanniz0r** [comment]
Consider it done my friend :3

**Comment by Maximilian1021** [comment]
#REOPEND 

Der Time Button ist wenn man ungenau hovert sehr am zittern :)
